# Generated by Django 5.1 on 2024-08-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('biografia', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('cursos', models.ManyToManyField(to='blog.curso')),
                ('interesses', models.ManyToManyField(to='blog.interesse')),
            ],
        ),
        migrations.DeleteModel(
            name='Sobre',
        ),
    ]
